/**
 * AboutPanel — explains the simulation to patients.
 * Shown in the patient watch view sidebar or as a collapsible section.
 */
import { Info } from "lucide-react";

export function AboutPanel() {
  return (
    <aside className="rounded-2xl border border-line bg-panel/60 p-6 space-y-4">
      <div className="flex items-center gap-2">
        <Info className="h-4 w-4 text-accent shrink-0" />
        <h3 className="text-sm font-semibold text-ink">About this simulation</h3>
      </div>
      <div className="space-y-3 text-xs leading-relaxed text-muted">
        <p>
          You are watching a <span className="font-semibold text-ink">real-time educational simulation</span> of a hospital emergency department. This is <span className="text-critical font-semibold">not a real hospital</span> — all patients and events are generated by the simulator.
        </p>
        <p>
          An admin is currently operating the scenario from their device: adding patients, assigning doctors, managing ICU beds, dispatching ambulances, and discharging patients.
        </p>
        <p>
          The simulator uses a <span className="font-medium text-ink">priority queue</span> (binary heap) to order waiting patients by urgency and wait time. Assignments happen only when the admin chooses them.
        </p>
        <p className="text-muted/60 border-t border-line/40 pt-3">
          Hospital Emergency Simulator v2 · Built with React + Supabase · Educational use only
        </p>
      </div>
    </aside>
  );
}
